######################################################################
# Automatically generated by qmake (3.0) Wed Mar 19 23:01:15 2014
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += .

# Input
HEADERS += qwindow.h
SOURCES += qwindow.cc
