######################################################################
# Automatically generated by qmake (3.0) Thu Mar 20 22:32:06 2014
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += qwindow.cc
